language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
script: nosetests --with-coverage --cover-package=musketeers run_tests.py
install:
  - pip install requests
  - pip install coveralls
after_succes:
  coveralls
